<?php

use App\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Permission::insert([
            ['module_id' => 3, 'submodule_id' => 1, 'name' => 'item unpublished', 'slug' => 'item-unpublished', 'parent' => 'item'],
            ['module_id' => 3, 'submodule_id' => 1, 'name' => 'item unpublished edit', 'slug' => 'item-unpublished-edit', 'parent' => 'item'],
            ['module_id' => 3, 'submodule_id' => 1, 'name' => 'item unpublished delete', 'slug' => 'item-unpublished-delete', 'parent' => 'item'],
            ['module_id' => 3, 'submodule_id' => 1, 'name' => 'item published view', 'slug' => 'item-published-view', 'parent' => 'item'],
            ['module_id' => 3, 'submodule_id' => 1, 'name' => 'item published edit', 'slug' => 'item-published-edit', 'parent' => 'item'],
            ['module_id' => 3, 'submodule_id' => 1, 'name' => 'item published delete', 'slug' => 'item-published-delete', 'parent' => 'item'],
            ['module_id' => 3, 'submodule_id' => 2, 'name' => 'Tag create', 'slug' => 'tag-create', 'parent' => 'Tag'],
            ['module_id' => 3, 'submodule_id' => 2, 'name' => 'Tag edit', 'slug' => 'tag-edit', 'parent' => 'Tag'],
            ['module_id' => 3, 'submodule_id' => 2, 'name' => 'Tag delete', 'slug' => 'tag-delete', 'parent' => 'Tag'],
            ['module_id' => 3, 'submodule_id' => 3, 'name' => 'color create', 'slug' => 'color-create', 'parent' => 'color'],
            ['module_id' => 3, 'submodule_id' => 3, 'name' => 'color edit', 'slug' => 'color-edit', 'parent' => 'color'],
            ['module_id' => 3, 'submodule_id' => 3, 'name' => 'color delete', 'slug' => 'color-delete', 'parent' => 'color'],
            ['module_id' => 3, 'submodule_id' => 4, 'name' => 'size edit', 'slug' => 'size-edit', 'parent' => 'size'],
            ['module_id' => 3, 'submodule_id' => 4, 'name' => 'size create', 'slug' => 'size-create', 'parent' => 'size'],
            ['module_id' => 3, 'submodule_id' => 4, 'name' => 'size delete', 'slug' => 'size-delete', 'parent' => 'size'],
            ['module_id' => 3, 'submodule_id' => 5, 'name' => 'Unit create', 'slug' => 'unit-create', 'parent' => 'Unit'],
            ['module_id' => 3, 'submodule_id' => 5, 'name' => 'Unit edit', 'slug' => 'unit-edit', 'parent' => 'Unit'],
            ['module_id' => 3, 'submodule_id' => 5, 'name' => 'Unit delete', 'slug' => 'unit-delete', 'parent' => 'Unit'],
            ['module_id' => 3, 'submodule_id' => 6, 'name' => 'Brand', 'slug' => 'brand', 'parent' => 'Brand'],
            ['module_id' => 3, 'submodule_id' => 6, 'name' => 'Brand create', 'slug' => 'brand-create', 'parent' => 'Brand'],
            ['module_id' => 3, 'submodule_id' => 6, 'name' => 'Brand edit', 'slug' => 'brand-edit', 'parent' => 'Brand'],
            ['module_id' => 3, 'submodule_id' => 6, 'name' => 'Brand delete', 'slug' => 'brand-delete', 'parent' => 'Brand'],
            ['module_id' => 3, 'submodule_id' => 7, 'name' => 'Origin', 'slug' => 'origin', 'parent' => 'Origin'],
            ['module_id' => 3, 'submodule_id' => 7, 'name' => 'Origin create', 'slug' => 'origin-create', 'parent' => 'Origin'],
            ['module_id' => 3, 'submodule_id' => 7, 'name' => 'Origin edit', 'slug' => 'origin-edit', 'parent' => 'Origin'],
            ['module_id' => 3, 'submodule_id' => 7, 'name' => 'Origin delete', 'slug' => 'origin-delete', 'parent' => 'Origin'],
            ['module_id' => 3, 'submodule_id' => 8, 'name' => 'Collection Create', 'slug' => 'collection-create', 'parent' => 'Collection'],
            ['module_id' => 3, 'submodule_id' => 8, 'name' => 'Collection Edit', 'slug' => 'collection-edit', 'parent' => 'Collection'],
            ['module_id' => 3, 'submodule_id' => 8, 'name' => 'Collection delete', 'slug' => 'collection-delete', 'parent' => 'Collection'],
            ['module_id' => 3, 'submodule_id' => 9, 'name' => 'Category create', 'slug' => 'category-create', 'parent' => 'Category'],
            ['module_id' => 3, 'submodule_id' => 9, 'name' => 'Category edit', 'slug' => 'category-edit', 'parent' => 'Category'],
            ['module_id' => 3, 'submodule_id' => 10, 'name' => 'Subcategory create', 'slug' => 'subcategory-create', 'parent' => 'Subcategory'],
            ['module_id' => 3, 'submodule_id' => 10, 'name' => 'Subcategory edit', 'slug' => 'subcategory-edit', 'parent' => 'Subcategory'],
            ['module_id' => 3, 'submodule_id' => 10, 'name' => 'Subcategory delete', 'slug' => 'subcategory-delete', 'parent' => 'Subcategory'],
            ['module_id' => 3, 'submodule_id' => 11, 'name' => 'Childcategory create', 'slug' => 'childcategory-create', 'parent' => 'Childcategory'],
            ['module_id' => 3, 'submodule_id' => 11, 'name' => 'Childcategory edit', 'slug' => 'childcategory-edit', 'parent' => 'Childcategory'],
            ['module_id' => 3, 'submodule_id' => 11, 'name' => 'Childcategory delete', 'slug' => 'childcategory-delete', 'parent' => 'Childcategory'],
            ['module_id' => 3, 'submodule_id' => 12, 'name' => 'Warranty create', 'slug' => 'warranty-create', 'parent' => 'Warranty'],
            ['module_id' => 3, 'submodule_id' => 12, 'name' => 'Warranty edit', 'slug' => 'warranty-edit', 'parent' => 'Warranty'],
            ['module_id' => 3, 'submodule_id' => 12, 'name' => 'Warranty delete', 'slug' => 'warranty-delete', 'parent' => 'Warranty'],
            ['module_id' => 4, 'submodule_id' => 13, 'name' => 'vat edit', 'slug' => 'vat-edit', 'parent' => 'vat'],
            ['module_id' => 4, 'submodule_id' => 13, 'name' => 'vat delete', 'slug' => 'vat-delete', 'parent' => 'vat'],
            ['module_id' => 4, 'submodule_id' => 14, 'name' => 'Commission List edit', 'slug' => 'commission-list-edit', 'parent' => 'Commission'],
            ['module_id' => 4, 'submodule_id' => 14, 'name' => 'Commission List delete', 'slug' => 'commission-list-delete', 'parent' => 'Commission'],
            ['module_id' => 4, 'submodule_id' => 15, 'name' => 'Delivery size create', 'slug' => 'delivery-size-create', 'parent' => 'Delivery'],
            ['module_id' => 4, 'submodule_id' => 15, 'name' => 'Delivery size edit', 'slug' => 'delivery-size-edit', 'parent' => 'Delivery'],
            ['module_id' => 4, 'submodule_id' => 15, 'name' => 'Delivery size delete', 'slug' => 'delivery-size-delete', 'parent' => 'Delivery'],
            ['module_id' => 5, 'submodule_id' => 16, 'name' => 'Add Sller', 'slug' => 'add-sller', 'parent' => 'Seller'],
            ['module_id' => 5, 'submodule_id' => 16, 'name' => 'All Seller', 'slug' => 'all-seller', 'parent' => 'Seller'],
            ['module_id' => 5, 'submodule_id' => 16, 'name' => 'Seller edit', 'slug' => 'seller-edit', 'parent' => 'Seller'],
            ['module_id' => 5, 'submodule_id' => 16, 'name' => 'Seller view', 'slug' => 'seller-view', 'parent' => 'Seller'],
            ['module_id' => 5, 'submodule_id' => 16, 'name' => 'Seller delete', 'slug' => 'seller-delete', 'parent' => 'Seller'],
            ['module_id' => 5, 'submodule_id' => 16, 'name' => 'Premium Seller', 'slug' => 'premium-seller', 'parent' => 'Seller'],
            ['module_id' => 6, 'submodule_id' => 17, 'name' => 'Add Agent', 'slug' => 'add-agent', 'parent' => 'Agent'],
            ['module_id' => 6, 'submodule_id' => 17, 'name' => 'Agent List', 'slug' => 'agent-list', 'parent' => 'Agent'],
            ['module_id' => 6, 'submodule_id' => 17, 'name' => 'Agent view', 'slug' => 'agent-view', 'parent' => 'Agent'],
            ['module_id' => 6, 'submodule_id' => 17, 'name' => 'Agent delete', 'slug' => 'agent-delete', 'parent' => 'Agent'],
            ['module_id' => 7, 'submodule_id' => 18, 'name' => 'Customer view', 'slug' => 'customer-view', 'parent' => 'Customer'],
            ['module_id' => 7, 'submodule_id' => 18, 'name' => 'Customer edit', 'slug' => 'customer-edit', 'parent' => 'Customer'],
            ['module_id' => 7, 'submodule_id' => 18, 'name' => 'Customer delete', 'slug' => 'customer-delete', 'parent' => 'Customer'],
            ['module_id' => 8, 'submodule_id' => 21, 'name' => 'Admin Create', 'slug' => 'admin-create', 'parent' => 'Admin'],
            ['module_id' => 8, 'submodule_id' => 21, 'name' => 'Admin edit', 'slug' => 'admin-edit', 'parent' => 'Admin'],
            ['module_id' => 8, 'submodule_id' => 21, 'name' => 'Admin delete', 'slug' => 'admin-delete', 'parent' => 'Admin'],
            ['module_id' => 9, 'submodule_id' => 22, 'name' => 'Blog Create', 'slug' => 'blog-create', 'parent' => 'Blog'],
            ['module_id' => 9, 'submodule_id' => 22, 'name' => 'Blog view', 'slug' => 'blog-view', 'parent' => 'Blog'],
            ['module_id' => 9, 'submodule_id' => 22, 'name' => 'Blog edit', 'slug' => 'blog-edit', 'parent' => 'Blog'],
            ['module_id' => 10, 'submodule_id' => 36, 'name' => 'Coupons create', 'slug' => 'coupons-create', 'parent' => 'Coupons'],
            ['module_id' => 10, 'submodule_id' => 36, 'name' => 'Coupons edit', 'slug' => 'coupons-edit', 'parent' => 'Coupons'],
            ['module_id' => 10, 'submodule_id' => 36, 'name' => 'Coupons delete', 'slug' => 'coupons-delete', 'parent' => 'Coupons'],
            ['module_id' => 10, 'submodule_id' => 42, 'name' => 'Flash Sale create', 'slug' => 'flash-sale-create', 'parent' => 'Flash'],
            ['module_id' => 10, 'submodule_id' => 42, 'name' => 'Flash Sale edit', 'slug' => 'flash-sale-edit', 'parent' => 'Flash'],
            ['module_id' => 10, 'submodule_id' => 42, 'name' => 'Flash Sale Delete', 'slug' => 'flash-sale-delete', 'parent' => 'Flash'],
            ['module_id' => 12, 'submodule_id' => 38, 'name' => 'unpublished comment view', 'slug' => 'unpublished-comment-view', 'parent' => 'unpublished'],
            ['module_id' => 12, 'submodule_id' => 38, 'name' => 'unpublished comment delete', 'slug' => 'unpublished-comment-delete', 'parent' => 'unpublished'],
            ['module_id' => 12, 'submodule_id' => 39, 'name' => 'Published comment edit', 'slug' => 'published-comment-edit', 'parent' => 'Published'],
            ['module_id' => 12, 'submodule_id' => 39, 'name' => 'Published comment delete', 'slug' => 'published-comment-delete', 'parent' => 'Published'],
            ['module_id' => 13, 'submodule_id' => 46, 'name' => 'Social Link Save', 'slug' => 'social-link-save', 'parent' => 'Social'],
            ['module_id' => 14, 'submodule_id' => 26, 'name' => 'Banner create', 'slug' => 'banner-create', 'parent' => 'Banner'],
            ['module_id' => 14, 'submodule_id' => 26, 'name' => 'Banner edit', 'slug' => 'banner-edit', 'parent' => 'Banner'],
            ['module_id' => 14, 'submodule_id' => 26, 'name' => 'Banner delete', 'slug' => 'banner-delete', 'parent' => 'Banner'],
            ['module_id' => 14, 'submodule_id' => 27, 'name' => 'Slider create', 'slug' => 'slider-create', 'parent' => 'Slider'],
            ['module_id' => 14, 'submodule_id' => 27, 'name' => 'Slider edit', 'slug' => 'slider-edit', 'parent' => 'Slider'],
            ['module_id' => 14, 'submodule_id' => 27, 'name' => 'Slider delete', 'slug' => 'slider-delete', 'parent' => 'Slider'],
            ['module_id' => 14, 'submodule_id' => 28, 'name' => 'Quick Page view', 'slug' => 'quick-page-view', 'parent' => 'Quick'],
            ['module_id' => 14, 'submodule_id' => 28, 'name' => 'Quick Page create', 'slug' => 'quick-page-create', 'parent' => 'Quick'],
            ['module_id' => 14, 'submodule_id' => 28, 'name' => 'Quick Page edit', 'slug' => 'quick-page-edit', 'parent' => 'Quick'],
            ['module_id' => 14, 'submodule_id' => 28, 'name' => 'Quick Page delete', 'slug' => 'quick-page-delete', 'parent' => 'Quick'],
            ['module_id' => 14, 'submodule_id' => 29, 'name' => 'Information Save', 'slug' => 'information-save', 'parent' => 'Information'],
            ['module_id' => 14, 'submodule_id' => 30, 'name' => 'SEO Key Word Save', 'slug' => 'seo-key-word-save', 'parent' => 'SEO'],
            ['module_id' => 15, 'submodule_id' => 31, 'name' => 'SMS Config Save', 'slug' => 'sms-config-save', 'parent' => 'SMS'],
            ['module_id' => 15, 'submodule_id' => 32, 'name' => 'Email Config Save', 'slug' => 'email-config-save', 'parent' => 'Email'],
            ['module_id' => 16, 'submodule_id' => 33, 'name' => 'Division create', 'slug' => 'division-create', 'parent' => 'Division'],
            ['module_id' => 16, 'submodule_id' => 33, 'name' => 'Division edit', 'slug' => 'division-edit', 'parent' => 'Division'],
            ['module_id' => 16, 'submodule_id' => 33, 'name' => 'Division delete', 'slug' => 'division-delete', 'parent' => 'Division'],
            ['module_id' => 16, 'submodule_id' => 34, 'name' => 'City create', 'slug' => 'city-create', 'parent' => 'City'],
            ['module_id' => 16, 'submodule_id' => 34, 'name' => 'City edit', 'slug' => 'city-edit', 'parent' => 'City'],
            ['module_id' => 16, 'submodule_id' => 34, 'name' => 'City delete', 'slug' => 'city-delete', 'parent' => 'City'],
            ['module_id' => 16, 'submodule_id' => 35, 'name' => 'Area create', 'slug' => 'area-create', 'parent' => 'Area'],
            ['module_id' => 16, 'submodule_id' => 35, 'name' => 'Area edit', 'slug' => 'area-edit', 'parent' => 'Area'],
            ['module_id' => 16, 'submodule_id' => 35, 'name' => 'Area delete', 'slug' => 'area-delete', 'parent' => 'Area'],
            ['module_id' => 9, 'submodule_id' => 22, 'name' => 'Blog delete', 'slug' => 'blog-delete', 'parent' => 'Blog'],
            ['module_id' => 3, 'submodule_id' => 1, 'name' => 'item published', 'slug' => 'item-published', 'parent' => 'item'],
            ['module_id' => 3, 'submodule_id' => 9, 'name' => 'Category delete', 'slug' => 'category-delete', 'parent' => 'Category'],
            ['module_id' => 6, 'submodule_id' => 17, 'name' => 'Agent edit', 'slug' => 'agent-edit', 'parent' => 'Agent'],
            ['module_id' => 8, 'submodule_id' => 21, 'name' => 'Admin permission', 'slug' => 'admin-permission', 'parent' => 'Admin'],
            ['module_id' => 2, 'submodule_id' => 53, 'name' => 'Withdraw Trasanction Edit', 'slug' => 'withdraw-trasanction-edit', 'parent' => 'Withdraw '],
            ['module_id' => 2, 'submodule_id' => 53, 'name' => 'Withdraw Trasanction Delete', 'slug' => 'withdraw-trasanction-delete', 'parent' => 'Withdraw '],
            ['module_id' => 1, 'submodule_id' => 47, 'name' => 'Pending Order Show', 'slug' => 'pending-order-show', 'parent' => 'Pending Order'],
            ['module_id' => 1, 'submodule_id' => 47, 'name' => 'Pending Order Edit', 'slug' => 'pending-order-edit', 'parent' => 'Pending Order'],
            ['module_id' => 1, 'submodule_id' => 47, 'name' => 'Pending Order Delete', 'slug' => 'pending-order-delete', 'parent' => 'Pending Order'],
            ['module_id' => 1, 'submodule_id' => 48, 'name' => 'Waiting Order Show', 'slug' => 'waiting-order-show', 'parent' => 'Waiting Order '],
            ['module_id' => 1, 'submodule_id' => 48, 'name' => 'Waiting Order Edit', 'slug' => 'waiting-order-edit', 'parent' => 'Waiting Order '],
            ['module_id' => 1, 'submodule_id' => 48, 'name' => 'Waiting Order Delete', 'slug' => 'waiting-order-delete', 'parent' => 'Waiting Order '],
            ['module_id' => 1, 'submodule_id' => 49, 'name' => 'Order NO Delivery Show', 'slug' => 'order-no-delivery-show', 'parent' => 'Order NO Delivery'],
            ['module_id' => 1, 'submodule_id' => 49, 'name' => 'Order NO Delivery Delete', 'slug' => 'order-no-delivery-delete', 'parent' => 'Order NO Delivery'],
            ['module_id' => 1, 'submodule_id' => 50, 'name' => 'Order NOT Delivery Show', 'slug' => 'order-not-delivery-show', 'parent' => 'Order Not Delivery'],
            ['module_id' => 1, 'submodule_id' => 50, 'name' => 'Order NOT Delivery Edit', 'slug' => 'order-not-delivery-edit', 'parent' => 'Order Not Delivery'],
            ['module_id' => 1, 'submodule_id' => 50, 'name' => 'Order NOT Delivery Delete', 'slug' => 'order-not-delivery-delete', 'parent' => 'Order Not Delivery'],
            ['module_id' => 1, 'submodule_id' => 51, 'name' => 'Order Delivered Show', 'slug' => 'order-delivered-show', 'parent' => 'Order-Delivered'],
            ['module_id' => 1, 'submodule_id' => 51, 'name' => 'Order Delivered Delete', 'slug' => 'order-delivered-delete', 'parent' => 'Order-Delivered'],
            ['module_id' => 1, 'submodule_id' => 52, 'name' => 'Order Cancelled Show', 'slug' => 'order-cancelled-show', 'parent' => 'Order'],
            ['module_id' => 1, 'submodule_id' => 52, 'name' => 'Order Cancelled Delete', 'slug' => 'order-cancelled-delete', 'parent' => 'Order']
        ]);
    }
}
